name: 定期更新赞助者名单

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    env:
      SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.AFDIAN_ID }}
      SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}
      SPONSORKIT_AFDIAN_EXECHANGERATE: '1'
      AFDIAN_EXECHANGERATE: '1'
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3

      - run: |
          npm i yarn -g
          yarn

      - name: Build Sponsorkit
        run: yarn build
        
      - name: Run Sponsorkit script
        run: node ./dist/cli.cjs
        
      - name: Install coscmd
        run: sudo pip install coscmd
            
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: sponsor-1306537081
          REGION: ap-beijing
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        
      - name: Upload
        run: coscmd upload -r ./sponsorkit/ Sponsor
